In [1]:
import pandas as pd
datafile=pd.read_csv ("https://raw.githubusercontent.com/Psyc3000A/Data/refs/heads/main/sleep.csv")
datafile.groupby('group').describe()

          A                                                extra        ...  \
      count  mean      std   min    25%   50%    75%   max count  mean  ...
group                                                                   ...
1      10.0   5.5  3.02765   1.0   3.25   5.5   7.75  10.0  10.0  0.75  ...
2      10.0  15.5  3.02765  11.0  13.25  15.5  17.75  20.0  10.0  2.33  ...

                    ID
        75%  max count mean      std  min   25%  50%   75%   max
group
1      1.70  3.7  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0
2      4.15  5.5  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0

[2 rows x 24 columns]

In [2]:
!mamba install pandas

/bin/bash: line 1: mamba: command not found

In [3]:
import pandas as pd, pingouin as pg
nhanes=pd.read_csv("https://raw.githubusercontent.com/Psyc3000A/Data/refs/heads/main/nhanes.csv")
pg.chi2_independence(nhanes, x="HowOftenDoYouFeelDepressed", y="EverToldDoctorHadTroubleSleeping")

/tmp/ipykernel_1936/3090870859.py:2: DtypeWarning: Columns (141: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  nhanes=pd.read_csv("https://raw.githubusercontent.com/Psyc3000A/Data/refs/heads/main/nhanes.csv")

(EverToldDoctorHadTroubleSleeping          0.0         1.0
 HowOftenDoYouFeelDepressed
 0.0                               1866.324319  706.675681
 1.0                               1251.953274  474.046726
 2.0                                322.780537  122.219463
 3.0                                282.160964  106.839036
 4.0                                219.780905   83.219095,
 EverToldDoctorHadTroubleSleeping   0.0  1.0
 HowOftenDoYouFeelDepressed
 0.0                               2137  436
 1.0                               1236  490
 2.0                                264  181
 3.0                                199  190
 4.0                                107  196,
                  test    lambda        chi2  dof           pval    cramer  \
 0             pearson  1.000000  482.605128  4.0  3.872451e-103  0.240180
 1        cressie-read  0.666667  470.001830  4.0  2.057373e-100  0.237023
 2      log-likelihood  0.000000  456.026306  4.0   2.162749e-97  0.233473
 3       freeman-tukey -0.500000  454.265847  4.0   5.195324e-97  0.233022
 4  mod-log-likelihood -1.000000  459.397638  4.0   4.037531e-98  0.234334
 5              neyman -2.000000  490.147038  4.0  9.057074e-105  0.242050

    power
 0    1.0
 1    1.0
 2    1.0
 3    1.0
 4    1.0
 5    1.0  )

In [4]:
import pandas as pd
datafile=pd.read_csv ("https://raw.githubusercontent.com/Psyc3000A/Data/refs/heads/main/sleep.csv")
datafile.groupby('group').describe()

          A                                                extra        ...  \
      count  mean      std   min    25%   50%    75%   max count  mean  ...
group                                                                   ...
1      10.0   5.5  3.02765   1.0   3.25   5.5   7.75  10.0  10.0  0.75  ...
2      10.0  15.5  3.02765  11.0  13.25  15.5  17.75  20.0  10.0  2.33  ...

                    ID
        75%  max count mean      std  min   25%  50%   75%   max
group
1      1.70  3.7  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0
2      4.15  5.5  10.0  5.5  3.02765  1.0  3.25  5.5  7.75  10.0

[2 rows x 24 columns]

In [5]:
print("hello world")

hello world

In [6]:
print("chris is the best")

chris is the best